default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rabbitmq_consumer_development_<%= ENV['QUEUE_ID'] %>

test:
  <<: *default
  database: rabbitmq_consumer_test_<%= ENV['QUEUE_ID'] %>

production:
  <<: *default
  database: rabbitmq_consumer_production_<%= ENV['QUEUE_ID'] %>
